### PR TITLE
secondary menu

### PR DESCRIPTION
**Pull request by Entkenntnis**

### CODE REVIEW

**Comment by elbotho** [comment]
Cool idea, plugin looks nice.

This issue might also affect us (no native scrolling with touch events). Did you try it on mobile yet?
https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/issues/54

**Comment by Entkenntnis** [comment]
mobile works quite fine (android/FF), the issue is about inertia scrolling, which is probably not a "must-have"

**Comment by elbotho** [comment]
@simonkoehl could you check experience on iOS?
https://deploy-preview-34--athene2-blue-gum.netlify.com/iframe.html?selectedKind=Components%20Gallery&selectedStory=Secondary%20Menu

we don't have native scrolling atm. but maybe it's good enough?

**Review by elbotho — DISMISSED** [review]
Could you change the markup to be more semantic?

```
<nav aria-label="Untermenü – Über Serlo">
<ul>
<li><a>…
```

----

Can we get rid of the outline/shadow on focused elements?

----

I'll try to figure out why  `<meta name="viewport" content="width=device-width, initial-scale=1">` is missing, that's probably why it's displaying so small on iOS

**Comment by Entkenntnis** [comment]
inerta scrolling is working now
Ready to merge?

**Review by elbotho — APPROVED** [review]
Lgtm.
Will set up a comparison with native scrolling out of interest.

**Pull request merged**
