### PR TITLE
running athene2 with next.js

### PR DESCRIPTION
**Pull request by Entkenntnis**

### CODE REVIEW

**Comment by Entkenntnis** [comment]
Usage: Check out this branch, run `yarn` and then run `yarn next` to start development server.
For production build run `yarn next:build` and `yarn next:start`
Example pages opens at `localhost:3000`

**Comment by elbotho** [comment]
Just to understand the architecture a little better: @Entkenntnis what do you think how much effort would it be to move to another SSR solution after some time or implement our own version without nextjs?

**Comment by Entkenntnis** [comment]
From my current understand it would take probably minimal 2 weeks up to 1 month to implement our own version of ssr (without nextjs) - doable, but not trivial

**Comment by elbotho** [comment]
@Entkenntnis oh, oh, did I break it?

**Comment by Entkenntnis** [comment]
Hm, the code looks fine, but netlify was too slow and reached the timeout ... maybe just try again?

**Comment by elbotho** [comment]
Strange: deployment of 3b1f57ba9b543ca1d7319a5729d61c36873e6734 took 13mins, 10 mins longer than the other builds. Will try to trigger another build.

**Comment by elbotho** [comment]
worked…

**Pull request merged**
